config/routes.rb
Emporium::Application.routes.draw do

  get "order/index"

  get "order/show"

  get "order/close"

  match 'checkout/thank_you', :to => 'checkout#thank_you'
  resources :checkout

  match 'catalog/latest', :to => 'catalog#latest'
  match 'about', :to => 'about#index'
  get "catalog/index"

  get "catalog/show"

  get "catalog/search"

  get "catalog/latest"

  namespace :admin do
    resources :books
    resources :author
    resources :publishers
    resources :order
  end

   get 'about/index'

  scope :module => "admin" do
    resources :books
  end

  root :to => 'catalog#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates_length_of :name, :in => 2..255
  validates_uniqueness_of :name
  attr_accessible :name
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publishers }
    end
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = Publisher.find(params[:id])
    @page_title = @publisher.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/1/edit
  def edit
    @publisher = Publisher.find(params[:id])
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(params[:publisher])
    respond_to do |format|
      if @publisher.save
        format.html { redirect_to([:admin, @publisher],
                                  :notice => 'Publisher was successfully created.') }
        format.json { render json: @publisher, status: :created,
                             location: @publisher }
      else
        format.html { render :action => "new" }
        format.json { render json: @publisher.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PUT /publishers/1
  # PUT /publishers/1.json
  def update
    @publisher = Publisher.find(params[:id])
    respond_to do |format|
      if @publisher.update_attributes(params[:publisher])
        format.html { redirect_to([:admin, @publisher],
                                  :notice => 'Publisher was successfully updated.') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render json: @publisher.errors,
                             :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to(admin_publishers_url) }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/views/admin/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', :action => 'show', :id => @publisher %> |
<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/index.html.erb
<h1>Listing publishers</h1>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= link_to 'Show', :action => 'show', :id => publisher %></td>
        <td><%= link_to 'Edit', :action => 'edit', :id => publisher %></td>
        <td><%= button_to 'Destroy', {:action => 'destroy', :id => publisher},
                          {:method => :delete, :confirm => 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Publisher', :action => 'new' %>

app/views/admin/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/show.html.erb
<dl>
  <dt>Name</dt>
  <dd><%= @publisher.name %></dd>
</dl>
<%= link_to 'Edit', :action => 'edit', :id => @publisher %> |
<%= link_to 'Back', admin_publishers_path %>